### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by starsoccer** [overhacked/waterfurnace-rs#1]
Are there any docs on how to use this or what exactly it does?

**Comment by overhacked** [comment]
This is up as a side project that use personally. It’s rather stable at this point. I can write up some quick docs for you if you have a WaterFurnace system that you’d like to use it with.On Aug 23, 2023, at 1:34 PM, starsoccer ***@***.***> wrote:﻿
Are there any docs on how to use this or what exactly it does?

**Comment by starsoccer** [comment]
Id love to see some docs and possibly contribute if your interested in that. I am not sure what the intent of the project is exactly though.

Right now I am making use of  another project for pulling data directly from the AID port, https://github.com/ccutrer/waterfurnace_aurora, I dont know any python though so now planning on doing much there

**Comment by overhacked** [comment]
So far intent has been read-only monitoring of multiple WaterFurnace systems via the undocumented Symphony WebSockets API. It holds a persistent websockets connection to Symphony and exposes a HTTP API to access system metrics.A future, but not active, goal has been to implement temperature and other parameter write access to be able to integrate with open home automation platforms.I’d be open to contributions. Let’s talk about in what direction.On Aug 23, 2023, at 3:11 PM, starsoccer ***@***.***> wrote:﻿
Id love to see some docs and possibly contribute if your interested in that. I am not sure what the intent of the project is exactly though.
Right now I am making use of  another project for pulling data directly from the AID port, https://github.com/ccutrer/waterfurnace_aurora, I dont know any python though so now planning on doing much there

**Comment by starsoccer** [comment]
Okay cool. While I did originally plan to go the route of using websockets to get data from the units, after using the above repo I mentioned I found its much better to just connect directly to the AID port

I totally get this isnt for everyone though but going this route does allow you to have control and provides a lot more details/sensor information

**Comment by overhacked** [comment]
If I’d known when I wrote this that there was an AID port library, I might have gone that way. On Aug 24, 2023, at 12:41 PM, starsoccer ***@***.***> wrote:﻿
Okay cool. While I did originally plan to go the route of using websockets to get data from the units, after using the above repo I mentioned I found its much better to just connect directly to the AID port
I totally get this isnt for everyone though but going this route does allow you to have control and provides a lot more details/sensor information

**Comment by starsoccer** [comment]
Yeah for sure, I mean wiring it is a pain but besides for that Its been working great so far. If you have any interesting in exploring that in rust that seems like it could be a fun project

**Comment by overhacked** [comment]
Maybe some day! I seldom have physical access to those systems right now; long story. Thanks for reaching out. If you ever do want to use or contribute to this project, let me know!
